# Generated by Django 5.0.6 on 2024-07-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchNo', models.CharField(max_length=80)),
                ('batchId', models.IntegerField()),
            ],
        ),
    ]
