# Generated by Django 5.0.6 on 2024-07-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperCode', models.CharField(max_length=8)),
                ('paperType', models.CharField(max_length=15)),
                ('papershtName', models.CharField(max_length=10)),
                ('paperName', models.CharField(max_length=24)),
            ],
        ),
        migrations.AlterField(
            model_name='batchmaster',
            name='batchNo',
            field=models.CharField(max_length=8),
        ),
    ]
