# Generated by Django 5.0.6 on 2024-07-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_studentinternaltrans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchmaster',
            name='batchId',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='batchmaster',
            name='batchNo',
            field=models.IntegerField(),
        ),
    ]
