# Generated by Django 5.0.6 on 2024-07-03 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_enrollmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmodel',
            name='cno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.coursemodel'),
        ),
        migrations.AlterField(
            model_name='enrollmodel',
            name='sno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.studentmodel'),
        ),
    ]
