# Generated by Django 5.0.6 on 2024-07-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examId', models.IntegerField()),
                ('examType', models.CharField(max_length=15)),
            ],
        ),
    ]
