# Generated by Django 5.0.6 on 2024-07-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_coursemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('cno', models.IntegerField()),
                ('jdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
