# Generated by Django 5.0.6 on 2024-07-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_enrollmodel_cno_alter_enrollmodel_sno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmodel',
            name='jdate',
            field=models.DateTimeField(),
        ),
    ]
